### ISSUE TITLE
Example of how to add capabilities / add capabilities via interface ?

### ISSUE THREAD

**Issue by iangregsondev** [tonicpow/go-paymail#38]
Hi,

I noticed there are a few feature requests for new capabilities.

What would be really nice is a quick document/example of how to add capabilities.

This would enable the easy extension of the library and allow others to give back to the project by adding additional standard ones.

What would be great is to be able to create the extensions/capabilities outside of the actually go-paymail - and add the ability to add new capabilities without touching the go-paymail app. Maybe some interface or something?

Great project though!

Going to have a play tomorrow :-)

Cheers

**Comment by mrz1836** [comment]
Excellent idea @iangregsondev - submit a PR if you have a proposition for how to add the capabilities. I'll have some time next this week to take a stab at integrating a flexible capabilities feature.

**Comment by mrz1836** [comment]
The `server` package is getting a refactor. Now, capabilities is a `map[string]interface{}` which you can extend ;-)
